### ISSUE TITLE
WARNING: No feed for package 'rtl8821ce-firmware' found

### ISSUE THREAD

**Issue by dausruddin** [Pix13/openwrt-rtw88-usb-feed#1]
Hi. After reading an interesting conversation in https://github.com/jayanta525/rk3328-rock-pi-e/issues/1, I wanted to try it for my Nanopi R2S.

But I am getting this warning
```
WARNING: No feed for package 'rtl8821ce-firmware' found
```

Do I need `rtl8821ce-firmware`? If yes, where do I get them?
I am just a casual user trying to build my own firmware, so treat me as a newbie :)

Thanks!

**Comment by dausruddin** [comment]
Oh, also I am using openwrt latest snapshot.

**Comment by dausruddin** [comment]
So I removed the dependencies and it builds successfully. But 8811CU device won't work.

**Comment by Pix13** [comment]
Hi @dausruddin, for the missing firmware, you will need to add these two commits/patches to your tree: https://github.com/Pix13/rk3328-rock-pi-e/commit/ef2915dfd2e8c1bb27136376718b041bd8679bc6 and https://github.com/Pix13/rk3328-rock-pi-e/commit/4026129826f33f3dbde533ee6eb67fe9926b1912

This will take care of having thr rtw88-usb package available in your OpenWRT tree. As for the driver itself, it does not work yet :)

Please follow my issue here: https://github.com/ulli-kroll/rtw88-usb/issues/12 and more importantly, the branch backports ( https://github.com/ulli-kroll/rtw88-usb/tree/backports ) which is the one that will/should work on OpenWRT

**Comment by dausruddin** [comment]
Oh okay, thanks. Seems that I won't be able to do anything as it is out of my capability.

Anyway, I want to mention that https://github.com/immortalwrt/immortalwrt is working fine, at least on my friend's R2S. He also tried https://github.com/quintus-lab/OpenWRT-R2S-R4S which can be seen pulling RTL8821CU driver source from immortalwrt repo, and got them working.

**Comment by Pix13** [comment]
Well i got the old driver working too, but it only works as a client wifi, not in access point ( because of the missing newest mac80211 api). I have hope, i'm badgering the new rt88-usb developper to have the driver working :)

**Comment by dausruddin** [comment]
I'll keep an eye then. Thanks!
