### ISSUE TITLE
openwrt compile with error about fsleep()

### ISSUE THREAD

**Issue by georgefang73** [Pix13/openwrt-rtw88-usb-feed#2]
Hi, compiling openwrt with this feed ends up with an error says that: 

"
rtw8822c.c:1482:2: error: implicit declaration of function 'fsleep'; did you mean 'ssleep'? [-Werror=implicit-function-declaration]
  fsleep(1000);
  ^~~~~~
  ssleep
cc1: some warnings being treated as errors
"

Can you tell some methods to fix it? Thanks a lot.

**Comment by georgefang73** [comment]
I'm using this feed with openwrt master tree

**Comment by Pix13** [comment]
Hi ! Hard to tell, i'm building only 8821cu for my SBC, and i don't know the state of the 8822cu chip in the rtw88-usb development 

See issue https://github.com/ulli-kroll/rtw88-usb/issues/4 that says "currently disabled", maybe you should try to open an issue in the driver source repo, as it seems related to a missing update on your chip

**Comment by georgefang73** [comment]
o i c, thanks for notice :)

**Comment by georgefang73** [comment]
Ok I figured out the problem.
Openwrt for my router use a older kernel so that i have to use the backports tree

**Comment by Pix13** [comment]
Aaah i was wondering about that :) Glad it works out!
